### ISSUE TITLE
Pokemon Let's Go saving issue

### ISSUE THREAD

**Issue by yair2000** [yuzu-emu/yuzu-mainline#1]
There's an issue regarding saving the progress in Pokemon Let's Go games.

The game starts normally, but when I want to save it, it freezes and the percent has skyrocketed to around 1000%.

I tried it on yuzu build, "yuzu 18" and an older yuzu canary build, "yuzu canary 2681-HEAD-fdecfac"

These are my specs (Laptop Specs)
Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Nvidia Geforce 840M
Windows

**Comment by chris062689** [comment]
Please move this issue to the master branch, as issue creation is not supported here.
